### ISSUE TITLE
Delete Photos

### ISSUE THREAD

**Issue by ajheisler** [zhxie/edancemarket-6024#3]
I am unable to delete photos. When I click on the delete photo button, nothing happens.

**Comment by zhxie** [comment]
Fixed via
https://github.com/zhxie/edancemarket-6024/commit/13d85fe967a71b25b6644deaf36defcad53b762d

**Comment by ajheisler** [comment]
I'm still not able to delete photos. I just tested it and I click on delete and it moves the photos below but doesn't remove the picture.

**Comment by zhxie** [comment]
Ah I think I forgot to deploy. Try it now?

**Comment by ajheisler** [comment]
It works!!!!!!!!!!!! Yay!
